export default {
  eng: {
    permissionsNotProvide: "Not count with permissions to view this area",
    errorNotFound: "Error 404 not found!",
    returnHomeButton: "Return to home",
    returnBackButton: "Back",
    exampleFullNameIndicator: "Loren ipsum",
    exampleCardIDIndicator: "2202202...",
    fieldAbreviationSchoolName : "U.E GONZU",
    fieldFullNameSchool : "U.E Cardenal González Zumarraga",
    fieldFullNameSchoolLegal : "Unidad Educativa Cardenal González Zumarraga",
    fieldWelcomeHere : "Bienvenidos reciban un cordial saludo de la",
    fieldElections: "Elections",
    fieldEmailIndicator: "Email",
    fieldPasswordIndicator: "Password",
    fieldFullnameIndicator: "Full name",
    fieldCardIDindicator: "Card identity",
    fieldGenderIndicator: "Gender",
    fieldPermissionsIndicator: "Permissions",
    fieldteacherAssignatureIndicator: "Teacher",
    fieldteacherTutorIndicator: "Tutor",
    fieldAccountTypeIndicator: "Account type",
    fieldChildrenCountIndicator: "Number of students represented",
    buttonViewProfileIndicator: "View profile",
    buttonNextIndicator: "Next",
    buttonConfirmIndicator: "Confirm",
    buttonBackIndicator: "Back",
    buttonReloadPageIndicator: "Reload",
    buttonLoadMoreIndicator: "Load more ...",
    buttonReadIndicator: "Read"
  },
  es: {
    permissionsNotProvide: "No cuenta con permisos necesarios para ver esta área",
    errorNotFound: "Error 404 no encontrado!",
    returnHomeButton: "Regresar al Inicio",
    returnBackButton: "Atrás",
    exampleFullNameIndicator: "Loren ipsum",
    exampleCardIDIndicator: "2202202...",
    fieldAbreviationSchoolName : "U.E GONZU",
    fieldFullNameSchool : "U.E Cardenal González Zumarraga",
    fieldFullNameSchoolLegal : "Unidad Educativa Cardenal González Zumarraga",
    fieldWelcomeHere : "Bienvenidos reciban un cordial saludo de la",
    fieldElections: "Elecciones",
    fieldEmailIndicator: "Correo",
    fieldPasswordIndicator: "Contraseña",
    fieldFullnameIndicator: "Nombres y Apellidos",
    fieldCardIDindicator: "Número de cédula",
    fieldGenderIndicator: "Género",
    fieldPermissionsIndicator: "Permisos",
    fieldteacherAssignatureIndicator: "Profesor/a",
    fieldteacherTutorIndicator: "Tutor/a",
    fieldAccountTypeIndicator: "Tipo de cuenta",
    fieldChildrenCountIndicator: "Número de estudiantes representados",
    buttonViewProfileIndicator: "Ver perfil",
    buttonNextIndicator: "Siguiente",
    buttonConfirmIndicator: "Confirmar",
    buttonBackIndicator: "Atrás",
    buttonReloadPageIndicator: "Recargar",
    buttonLoadMoreIndicator: "Cargar más ...",
    buttonReadIndicator: "Leer"
  }
};
