export default {
  eng: {
    tolltipInitialsCampaign: "Initials (separar con un punto)",
    permissionsNotProvide: "Not count with permissions to view this area",
    errorNotFound: "Error 404 not found!",
    returnHomeButton: "Return to home",
    returnBackButton: "Back",
    exampleFullNameIndicator: "Loren ipsum",
    exampleCardIDIndicator: "2202202...",
    fieldAbreviationSchoolName: "U.E GONZU",
    fieldFullNameSchool: "U.E Cardenal González Zumarraga",
    fieldFullNameSchoolLegal: "Unidad Educativa Cardenal González Zumarraga",
    fieldWelcomeHere: "Bienvenidos reciban un cordial saludo de la",
    fieldElections: "Elections",
    fieldEmailIndicator: "Email",
    fieldPasswordIndicator: "Password",
    fieldFullnameIndicator: "Full name",
    fieldCardIDindicator: "Card identity",
    fieldGenderIndicator: "Gender",
    fieldPermissionsIndicator: "Permissions",
    fieldteacherAssignatureIndicator: "Teacher",
    fieldteacherTutorIndicator: "Tutor",
    fieldAccountTypeIndicator: "Account type",
    fieldStatusIndicatorActive: "Active",
    fieldStatusIndicatorInactive: "Inactive",
    fieldStatusIndicatorClose: "Closed",
    fieldStatusIndicatorOpen: "Open",
    fieldStatusIndicatorListening: "Listening",
    fieldChildrenCountIndicator: "Number of students represented",
    buttonViewProfileIndicator: "View profile",
    buttonNextIndicator: "Next",
    buttonConfirmIndicator: "Confirm",
    buttonBackIndicator: "Back",
    buttonCloseIndicator: "Close",
    buttonSaveIndicator: "Save",
    buttonAddListIndicator: "Add list",
    buttonAddCandidateIndicator: "Add candidate",
    buttonCreateCampaignIndicator: "Create new campaign",
    buttonReloadPageIndicator: "Reload",
    buttonLoadMoreIndicator: "Load more ...",
    buttonReadIndicator: "Read",
    unxpectedError: "Unxpected error",
    alertCompleteAllFields: "Complete all fields",
    alertEmptyCandidats: "Dont have any candidate added"
  },
  es: {
    tolltipInitialsCampaign: "Iniciales (separar con un punto)",
    permissionsNotProvide: "No cuenta con permisos necesarios para ver esta área",
    errorNotFound: "Error 404 no encontrado!",
    returnHomeButton: "Regresar al Inicio",
    returnBackButton: "Atrás",
    exampleFullNameIndicator: "Loren ipsum",
    exampleCardIDIndicator: "2202202...",
    fieldAbreviationSchoolName: "U.E GONZU",
    fieldFullNameSchool: "U.E Cardenal González Zumarraga",
    fieldFullNameSchoolLegal: "Unidad Educativa Cardenal González Zumarraga",
    fieldWelcomeHere: "Bienvenidos reciban un cordial saludo de la",
    fieldElections: "Elecciones",
    fieldEmailIndicator: "Correo",
    fieldPasswordIndicator: "Contraseña",
    fieldFullnameIndicator: "Nombres y Apellidos",
    fieldCardIDindicator: "Número de cédula",
    fieldGenderIndicator: "Género",
    fieldPermissionsIndicator: "Permisos",
    fieldteacherAssignatureIndicator: "Profesor/a",
    fieldteacherTutorIndicator: "Tutor/a",
    fieldAccountTypeIndicator: "Tipo de cuenta",
    fieldStatusIndicatorActive: "Activo",
    fieldStatusIndicatorInactive: "Inactivo",
    fieldStatusIndicatorClose: "Cerrado",
    fieldStatusIndicatorOpen: "Abierto",
    fieldStatusIndicatorListening: "Escuchando",
    fieldChildrenCountIndicator: "Número de estudiantes representados",
    buttonViewProfileIndicator: "Ver perfil",
    buttonNextIndicator: "Siguiente",
    buttonConfirmIndicator: "Confirmar",
    buttonBackIndicator: "Atrás",
    buttonCloseIndicator: "Cerrar",
    buttonSaveIndicator: "Guardar",
    buttonAddListIndicator: "Añadir lista",
    buttonAddCandidateIndicator: "Añadir candidato",
    buttonCreateCampaignIndicator: "Crear nueva campaña",
    buttonReloadPageIndicator: "Recargar",
    buttonLoadMoreIndicator: "Cargar más ...",
    buttonReadIndicator: "Leer",
    unxpectedError: "Error desconocido",
    alertCompleteAllFields: "Complete todos los campos",
    alertEmptyCandidats: "No tienes ningun candidato agregado"
  }
};
